export const APP_HEADER_HEIGHT = 56;

export const APP_MOBILE_HEADER_HEIGHT = 56;

export const APP_MOBILE_FOOTER_ACTIONS_HEIGHT = 70;

export const APP_SIDE_PANEL_PLACEHOLDER_WIDTH = 54;

export const APP_SIDE_PANEL_ITEM_HEIGHT = 52;
