name: check-code-quality
run-name: Validate `${{ github.actor }}` code quality
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  run-code-linters:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install modules
      run: npm i
    - name: Run ESLint and Typescript checking
      run: |
        npx tsc --noEmit
        npm run lint
    - name: Build demo
      run: npm run build --no-lint -d
      
