name: Cloud Build for Dev Branch

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY_JSON }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '>= 363.0.0'
        export_default_credentials: true

    - name: Run Cloud build
      run: |
        gcloud builds submit --config cloudbuild.dev.yaml --substitutions=_NEXT_PUBLIC_BASE_API=${{ vars.NEXT_PUBLIC_BASE_API_DEV }}